Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -66,6 +66,13 @@ jobs:
           APP_STORE_CONNECT_API_KEY_B64: ${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}
         run: bundle exec fastlane ios build_only --verbose
 
+      - name: Print Xcode build log
+        if: always()
+        run: |
+          echo "===== Xcode Build Log ====="
+          cat /Users/runner/Library/Logs/gym/SampleApp-SampleApp.log || echo "Log file not found"
+
+
       - name: Delete temporary keychain (cleanup)
         if: always()
         run: |
