Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,6 +32,18 @@ jobs:
             "in_house": false
           }' > api_key.json
 
+      - name: Validate match Git repo access
+        env:
+            GIT_URL: ${{ secrets.MATCH_GIT_URL }}
+        run: |
+            echo "Checking access to $GIT_URL"
+            if git ls-remote "$GIT_URL" &> /dev/null; then
+              echo "Git repo is accessible."
+            else
+              echo "Cannot access match Git repo: $GIT_URL"
+              exit 1
+            fi
+
       - name: Set up match and build with Fastlane
         env:
           MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
